[package]
name = "frequency-analysis"
version = "0.1.0"
edition = "2021"

[dependencies]
lindera-core = "0.24.0"
lindera-dictionary = "0.24.0"
lindera-tokenizer = {version = "0.24.0",features = ["ipadic"]}
csv = "1.1"
serde = { version = "1.0", features = ["derive"] }
anyhow = "1.0.95"